version: "3"
services:
  postgres:
    image: pgrouting/pgrouting:10-2.5-2.6.3
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    ports:
      - "5432:5432"

  web:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
    volumes:
      - .:/code/src
    ports:
      - "8000:8000"
    command: ./manage.py runserver 0.0.0.0:8000

volumes:
  postgres:
